"""add user role

Revision ID: 58ed6ac4c870
Revises: 9f0562f21986
Create Date: 2026-07-09 12:39:13.016032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '58ed6ac4c870'
down_revision: Union[str, Sequence[str], None] = '9f0562f21986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False))
    op.drop_constraint(op.f('users_ibfk_1'), 'users', type_='foreignkey')
    op.drop_column('users', 'department_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('users_ibfk_1'), 'users', 'department', ['department_id'], ['id'])
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
