"""add open_id to users

Revision ID: 735babff9a62
Revises: 3efdfa1d7ebe
Create Date: 2026-07-11 16:33:25.677564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '735babff9a62'
down_revision: Union[str, Sequence[str], None] = '3efdfa1d7ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('open_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'users', ['open_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'open_id')
    # ### end Alembic commands ###
