name: Enterprise AI Agent CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  test:

    runs-on: ubuntu-latest

    env:
      APP_NAME: EnterpriseAI
      APP_VERSION: 1.0.0

      MYSQL_HOST: localhost
      MYSQL_PORT: 3306